# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'About Us Banner',
            },
        ),
        migrations.CreateModel(
            name='Staff_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Supporters',
            },
        ),
        migrations.CreateModel(
            name='Supporter_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Supporter Section',
            },
        ),
    ]
