# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_director_history_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='staff_member',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
