# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-18 15:13
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='generic_pages_banner')),
            ],
            options={
                'verbose_name_plural': 'Generic Banner',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='generic_pages_post')),
                ('publisher_name', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
                ('author_first_name', models.CharField(max_length=200)),
                ('author_last_name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Generic Page',
            },
        ),
    ]
