# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-20 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(default='about_banner/no-banner-img.jpg', upload_to='our_work_banner')),
                ('sub_image', models.ImageField(default='our_work_banner/solutions.jpg', upload_to='our_work_banner')),
            ],
            options={
                'verbose_name_plural': 'Our Work Banner',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='partners/No_person-1.jpg', upload_to='partner')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Partnership_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Type of Partnership',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='partnership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='our_work.Partnership_Type'),
        ),
    ]
