# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'Our Work Banner',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('name', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Partnership_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Type of Partnership',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='partnership_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='our_work.Partnership_Type'),
        ),
    ]
