# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sub_image',
            field=models.ImageField(default='our_work_banner/solutions.jpg', upload_to='our_work_banner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(default='4073 Grace Ave', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='Bronx', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='coordinate',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.CharField(default='NY', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='zipcode',
            field=models.CharField(default='10466', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='about_banner/no-banner-img.jpg', upload_to='our_work_banner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default='partners/No_person-1.jpg', upload_to='partner'),
        ),
    ]
