# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partnership_type',
            name='text',
            field=models.TextField(),
        ),
    ]
