# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0002_auto_20180314_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='coordinate',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
