# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0003_auto_20180228_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='zipcode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
