# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0003_auto_20180314_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='coordinate',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
