# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0003_auto_20180416_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='affiliates/No_person-1.jpg', upload_to='affiliates')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='our_work.Partner')),
            ],
            options={
                'verbose_name_plural': 'Affiliates',
            },
        ),
    ]
