# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0005_auto_20180508_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='sub_section',
            options={'verbose_name_plural': 'Our Work Sub Sections'},
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sub_section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Sub Section Logo'),
        ),
    ]
