# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0006_auto_20180518_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_work_main_image')),
            ],
            options={
                'verbose_name_plural': 'Our Work Main Image',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='sub_image',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='our_work_banner/no-banner-img.jpg', upload_to='our_work_banner'),
        ),
    ]
