# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_work', '0007_auto_20180607_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_image',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
