# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_link', models.URLField()),
                ('publish_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(blank=True, max_length=5000)),
                ('author_first_name', models.CharField(max_length=200)),
                ('author_last_name', models.CharField(max_length=200)),
                ('is_inPress', models.BooleanField(default=False)),
                ('is_blogPost', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
