# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 18:52
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_blogPost',
            new_name='is_news',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='is_inPress',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='news',
            name='publisher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
