# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180222_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(default='news_banner/no-banner-img.jpg', upload_to='news_banner')),
            ],
            options={
                'verbose_name_plural': 'Publications Banner',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news_articles'),
        ),
    ]
