# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20180521_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publish',
            new_name='published',
        ),
    ]
