# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20180521_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_news',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published',
            new_name='publish',
        ),
    ]
