# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact_Section_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'Impact Section Carousel Images',
            },
        ),
        migrations.AddField(
            model_name='impact_section',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
