# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_auto_20180416_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'Main Logo',
            },
        ),
    ]
