# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impact_Caraousel_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(default='impact_banner/no-banner-img.jpg', upload_to='impact_caraousel')),
            ],
            options={
                'verbose_name_plural': 'Home Page Impact Section',
            },
        ),
    ]
