# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_impact_caraousel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.ImageField(default='about_banner/no-banner-img.jpg', upload_to='our_work_banner')),
            ],
            options={
                'verbose_name_plural': 'Email Authentication',
            },
        ),
    ]
