# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
