# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_delete_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar_Brand_Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=b'')),
            ],
            options={
                'verbose_name_plural': 'Main Logo',
            },
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name_plural': 'Partner Logo'},
        ),
    ]
