# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_auto_20180607_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impact_Section_Image',
        ),
        migrations.AlterModelOptions(
            name='impact_caraousel_image',
            options={'verbose_name_plural': 'Home Page Impact Caraousel Images'},
        ),
        migrations.AlterField(
            model_name='impact_caraousel_image',
            name='image',
            field=models.ImageField(default='impact_caraousel/no-banner-img.jpg', upload_to='impact_caraousel'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='here', upload_to='partner_logos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='navbar_brand_logo',
            name='image',
            field=models.ImageField(default='main_logo/jobsfirst_logo.png', upload_to='main_logo'),
        ),
    ]
