# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_auto_20180607_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='default')),
            ],
            options={
                'verbose_name_plural': 'Default Staff Image',
            },
        ),
    ]
