# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-08 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0011_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navbar_brand_logo',
            name='name',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
