# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('image', models.ImageField(default='publications_banner/no-banner-img.jpg', upload_to='publications_banner')),
            ],
            options={
                'verbose_name_plural': 'Publications Banner',
            },
        ),
    ]
