# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null='True', upload_to='Article'),
        ),
    ]
