# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20180306_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Media Banner'},
        ),
    ]
