# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20180306_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Publications Banner'},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null='True', upload_to='Article'),
        ),
    ]
