# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-21 18:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20180416_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
