# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, null='True', upload_to='Article/pdf'),
        ),
    ]
